# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: Setup Lab Dynamic Variables
  hosts: lab
  gather_facts: False
  connection: local

  tasks:
    - name: Save MAC Address
      set_fact:
        mac: "DON'T CARE"

- name: Clean up Hypervisor
  hosts: lab 
  become: true
  become_user: root
  gather_facts: false

  vars: 
    cleanup_cloud_images: false

  tasks: 
    - include:  tasks/provision/tasks/cleanup.yml
    - include:  tasks/network_bridge/tasks/cleanup.yml
    - include:  tasks/image_content/tasks/cleanup.yml
