# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: Setup Lab Dynamic Variables
  hosts: lab
  gather_facts: False
  connection: local

  tasks:
    - name: Generate MAC Address
      command: "python -c 'import random; print(\"52:54:00:{0}:{1}:{2}\".format(hex(random.randint(0,255))[2:], hex(random.randint(0,255))[2:], hex(random.randint(0,255))[2:]))'"
      register: gen_mac

    - name: Save MAC Address
      set_fact:
        mac: "{{ gen_mac.stdout }}"

- name: Hypervisor Setup
  hosts: hypervisor
  become: true
  become_user: root

  roles:
    - hypervisor_setup
    - network_bridge

- name: Cloud Image Download/Setup
  hosts: lab 
  become: true
  become_user: root
  gather_facts: False

  roles:
    - image_content 
    - provision
