[hypervisor]
127.0.0.1 ansible_connection=local

[hypervisor:vars]
libvirt_bridges=[{'name': 'minilab', 'forward': 'nat', 'bridge': 'virbr-100', 'domain': 'minilab.org', 'network': '192.168.100.0', 'broadcast': '192.168.100.255', 'ip_address': '192.168.100.254', 'ip_netmask': '255.255.255.0', 'dhcp_start': '192.168.100.1', 'dhcp_end': '192.168.100.253', 'dns_names': "{{ groups.lab | create_dns_names(hostvars) }}"}]

[lab:vars]
cloud_user_passwd="password"
#ssh_pub_key="ssh-rsa KEY user@HOST"

[lab]
fedora26 ram=512MB storage_extend=5GB extra_disk=5GB ip=192.168.100.1 host_image_uri="http://mirror.cc.vt.edu/pub/fedora/linux/releases/26/CloudImages/x86_64/images/Fedora-Cloud-Base-26-1.5.x86_64.qcow2" host_image_checksum="sha256:37a621dda65b04e8b6eee207088ff7697795cb2affdac13ed77166453989557c"
