---

- include_vars:
    file: roles/image_content/defaults/main.yml
  run_once: true

- name: Clean up Cloud user-data Files
  file: 
    path: "/tmp/{{ inventory_hostname }}/user-data" 
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root

- name: Clean up Cloud meta-data Files
  file: 
    path: "/tmp/{{ inventory_hostname }}/meta-data" 
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root

- name: Clean up Cloud user-data Files
  file: 
    path: "/tmp/{{ inventory_hostname }}/cidata.iso" 
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root

- name: Clean up host tmp dir
  file:
    path: "/tmp/{{ inventory_hostname }}"
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root

- name: Clean up Extra Image Disks
  file:
    path: "{{ libvirt_images_path }}/{{ inventory_hostname }}.disk"
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root
  when: "hostvars[inventory_hostname]['storage_extend'] is defined"

- name: Clean up Cloud Image
  file: 
    path: "{{ libvirt_images_path }}/{{ host_image_uri | basename }}"
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root
  when: "cleanup_cloud_images"

- name: Clean up Host Cloud Image
  file: 
    path: "{{ libvirt_images_path }}/{{ inventory_hostname }}.qcow" 
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root
  delay: 1
  retries: 5 
