---
- name: Create Networking Config
  template:
    src: config.xml.j2
    dest: "/tmp/{{ item.name }}.xml"
  with_items: "{{ libvirt_bridges }}"
  become: true

- virt_net:
    command: facts

# Be wary of the network name conflicting with similar names in your network list. 
- name: Create Virtual Network
  virt_net: 
    command: define 
    name: "{{ libvirt_bridges.0.name }}" 
    xml: "{{ lookup('file', '/tmp/{{ libvirt_bridges.0.name }}.xml') }}"
  when: "libvirt_bridges.0.name not in ansible_libvirt_networks"
  become: true

- name: Start Virtual Network
  virt_net: 
    command: start 
    name: "{{ item.name }}"
    state: active 
  with_items: "{{ libvirt_bridges }}"
  when: "libvirt_bridges.0.name not in ansible_libvirt_networks"
  become: true

- name: Setup Network Manager (on Hypervisor) - auto DNS
  template:
    src: dnsmasq_config.j2
    dest: "/etc/NetworkManager/dnsmasq.d/libvirt_{{ libvirt_bridges.0.name }}_dnsmasq.conf"
  with_items: "{{ libvirt_bridges }}"
  become: true

- name: Restart NetworkManager (enable DNS changes)
  service:
    name: NetworkManager
    state: restarted
  become: true

- pause:
    seconds: 15
#- debug:
#    msg: "Delete network with: sudo virsh net-destroy {{ libvirt_bridges.0.name }}; sudo virsh net-undefine {{ libvirt_bridges.0.name }}"
#  when: '"{{ libvirt_bridges.0.name }}" in "{{ ansible_libvirt_networks }}"'
