---

- include_vars:
    file: roles/network_bridge/defaults/main.yml
  run_once: true

- name: Stop the VM Network
  virt_net:
      name: "{{ libvirt_bridges[0].name }}"
      command: destroy
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root
  ignore_errors: yes

- name: Delete the VM Network
  virt_net:
      name: "{{ libvirt_bridges[0].name }}"
      command: undefine
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root
  ignore_errors: yes

- name: Clean up Network xml 
  file: 
    path: "/tmp/{{ libvirt_bridges[0].name }}.xml"
    state: absent
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"
  become: true
  become_user: root

- name: Clean up DNSMASQ configuration file
  file:
    path: "/etc/NetworkManager/dnsmasq.d/libvirt_{{ libvirt_bridges.0.name }}_dnsmasq.conf"
    state: absent
  become: true
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"

- name: Restart NetworkManager (disable DNS changes)
  service:
    name: NetworkManager
    state: restarted
  become: true
  delegate_to: "{{item}}"
  with_items: "{{groups['hypervisor']}}"

